import{db,save,today,touch,bump,exportData,importData,reset}from'./storage.js';
import{say,stop,listen,voices,supported,grade,keyPoints}from'./voice.js';
import{chat,aiReady,provider,SYSTEM}from'./ai.js';
import{answer as offlineAnswer}from'./offline.js';import{book}from'./book.js';import{topics}from'./data/topics.js';import{qa}from'./data/qa.js';import{pages}from'./data/pages.js';
const $=s=>document.querySelector(s),app=$('#app');
const esc=t=>String(t??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const sh=a=>[...a].sort(()=>Math.random()-.5),T=id=>topics.find(t=>t.id==id),rate=()=>+db.settings.rate;
const st=id=>db.t[id]=db.t[id]||{prac:null,quiz:null,known:{},miss:{}};
const tcards=t=>cardsOf(t).length;
const mastery=t=>{const s=st(t.id),k=Object.values(s.known).filter(Boolean).length,c=tcards(t);const v=[s.prac,s.quiz,k?Math.min(100,Math.round(100*k/c)):null].filter(x=>x!=null);return v.length?Math.round(v.reduce((a,b)=>a+b)/v.length):0};
const ring=(p,c='var(--p)',s=64)=>`<svg class="ring" width="${s}" height="${s}" viewBox="0 0 36 36"><circle cx="18" cy="18" r="15.9" fill="none" stroke="#ffffff30" stroke-width="3.5"/><circle cx="18" cy="18" r="15.9" fill="none" stroke="${c}" stroke-width="3.5" stroke-linecap="round" stroke-dasharray="${p} 100" transform="rotate(-90 18 18)"/><text x="18" y="21" text-anchor="middle" font-size="9" fill="currentColor" font-weight="700">${p}%</text></svg>`;
const bar=p=>`<div class="bar"><i style="width:${p}%"></i></div>`;
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('on');setTimeout(()=>t.classList.remove('on'),1800)};
const streak=()=>{let n=0,d=new Date();if(!db.days.includes(d.toISOString().slice(0,10)))d.setDate(d.getDate()-1);while(db.days.includes(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n};
const bt=b=>[b.h,b.t,...(b.i||[]),...(b.r||[]).map(r=>r.join(': ')),...(b.c||[]).flatMap(c=>[c[0],...c[1]])].filter(Boolean).join('. ');
const topicText=t=>`# ${t.no}. ${t.title}\n`+t.blocks.map(b=>`## ${b.h||b.k}\n${bt({...b,h:''})}`).join('\n');
const NAV=[['home','🏠','Home'],['learn','📖','Lessons'],['quiz','🧪','Quizzes'],['cards','🃏','Flashcards'],['oral','🎙️','Oral Q&A (65)'],['book','📚','Q&A Book'],['tutor','🤖','AI Tutor'],['saved','⭐','Saved & Notes'],['progress','📊','Progress'],['settings','⚙️','Settings & Profile']];
$('#nav').innerHTML=NAV.map(n=>`<a href="#${n[0]}" data-p="${n[0]}">${n[1]} ${n[2]}</a>`).join('');
$('#tabbar').innerHTML=[['home','🏠','Home'],['learn','📖','Learn'],['oral','🎙️','Oral'],['tutor','🤖','AI']].map(n=>`<a href="#${n[0]}" data-p="${n[0]}"><span>${n[1]}</span>${n[2]}</a>`).join('')+`<a href="#" data-a="menu"><span>☰</span>More</a>`;
const applySet=()=>{const s=db.settings,r=document.documentElement;r.dataset.theme=s.theme;r.style.setProperty('--fs',s.fs+'px');document.body.classList.toggle('nomo',!s.motion);const m=document.querySelector('meta[name=theme-color]');if(m)m.content=s.theme=='daylight'?'#eef2ff':'#0b1020'};
/* ---------- content renderers ---------- */
function blk(b,t,i){const bm=db.marks.includes(t.id+':'+i);const H=b.h?`<div class="bh"><h3>${esc(b.h)}</h3><button class="star" data-a="mark" data-id="${t.id}" data-i="${i}" aria-label="Bookmark">${bm?'★':'☆'}</button><button class="ico" data-a="readb" data-id="${t.id}" data-i="${i}" aria-label="Read aloud">🔊</button></div>`:'';let x='';
 switch(b.k){
 case'def':return`<div class="card blk def"><div class="lbl">${esc(b.h||'Definition')} · definition</div><div style="margin-top:6px">${esc(b.t)}</div></div>`;
 case'chips':x=`<div class="chips">${b.i.map(c=>`<span class="chip">${esc(c)}</span>`).join('')}</div>`;break;
 case'list':x=`<ul class="items">${b.i.map(c=>`<li>${esc(c)}</li>`).join('')}</ul>`;break;
 case'cols':x=`<div class="cols">${b.c.map(c=>`<div class="col"><h4>${esc(c[0])}</h4><ul>${c[1].map(y=>`<li>${esc(y)}</li>`).join('')}</ul></div>`).join('')}</div>`;break;
 case'table':x=`<table>${b.r.map(r=>`<tr><td>${esc(r[0])}</td><td>${esc(r[1])}</td></tr>`).join('')}</table>`;break;
 case'steps':x=`<ol class="steps">${b.i.map((c,j)=>`<li><span class="n">${j+1}</span><span class="t">${esc(c)}</span></li>`).join('')}</ol>`;break;
 case'say':return`<div class="card blk say"><div class="lbl">🗣️ ${esc(b.h)}</div><div style="margin-top:6px">“${esc(b.t)}”</div><button class="btn sm ghost" style="margin-top:10px" data-a="readb" data-id="${t.id}" data-i="${i}">🔊 Listen</button></div>`;
 case'warn':return`<div class="card blk warn">${H}<ul class="items">${b.i.map(c=>`<li>${esc(c)}</li>`).join('')}</ul></div>`;
 case'mem':return`<div class="card blk mem">🧠 Memory trick — ${esc(b.t)}</div>`}
 return`<div class="card blk">${H}${x}</div>`}
const cardsOf=t=>t.blocks.flatMap((b,bi)=>{const k=t.id+':'+bi,h=b.h||'';
 if(b.k=='def')return[{k,f:h+' — define it',b:b.t}];if(b.k=='table')return b.r.map((r,j)=>({k:k+'.'+j,f:`${h}: ${r[0]}`,b:r[1]}));
 if(b.k=='steps')return b.i.map((s,j)=>({k:k+'.'+j,f:`${h} — step ${j+1}`,b:s}));
 if(b.k=='cols')return b.c.map((c,j)=>({k:k+'.'+j,f:`${h}: ${c[0]}`,b:c[1].join(' · ')}));
 if(b.k=='list'||b.k=='chips')return[{k,f:`${h} — what are they?`,b:b.i.join(' · ')}];if(b.k=='say')return[{k,f:h,b:b.t}];return[]});
function genQuiz(t){const out=[],pick=(a,n)=>sh(a).slice(0,n);
 t.blocks.forEach(b=>{if(b.k=='table'&&b.r.length>1)b.r.forEach(r=>out.push({q:`${b.h}: ${r[0]}?`,a:r[1],o:sh([r[1],...pick(b.r.filter(x=>x!=r).map(x=>x[1]),3)])}));
 if((b.k=='list'||b.k=='chips')&&b.i.length>2){const other=t.blocks.filter(x=>x!=b&&x.i&&x.k!='steps'&&x.k!='warn').flatMap(x=>x.i);if(other.length>2){const it=b.i[Math.floor(Math.random()*b.i.length)];out.push({q:`Which belongs to "${b.h}"?`,a:it,o:sh([it,...pick(other.filter(x=>!b.i.includes(x)),3)])})}}
 if(b.k=='steps'&&b.i.length>3)for(let j=0;j<b.i.length-1;j+=2)out.push({q:`In "${b.h}", what comes AFTER: “${b.i[j].slice(0,90)}”?`,a:b.i[j+1],o:sh([b.i[j+1],...pick(b.i.filter((x,y)=>y!=j+1&&y!=j),3)])})});
 return pick(out.filter(q=>q.o.length>1),8)}
function qaQuiz(){return sh(qa).slice(0,10).map(x=>({q:x.q,a:x.a,id:x.n,o:sh([x.a,...sh(qa.filter(y=>y!=x)).slice(0,3).map(y=>y.a)])}))}
/* ---------- views ---------- */
const V={};let S={};
V.welcome=()=>`<div class="hero" style="min-height:70vh;display:flex;align-items:center;justify-content:center;text-align:center">
 <div style="max-width:520px;width:100%">
  <div style="font-size:56px;margin-bottom:10px">👋</div>
  <h1 style="font-size:clamp(30px,6vw,48px);margin:0 0 10px">What's your name?</h1>
  <p style="opacity:.85;margin-bottom:22px">Let's personalize your Caregiving Study Hub.</p>
  <div style="display:flex;gap:10px;max-width:420px;margin:auto">
   <input id="welcomeName" type="text" autocomplete="name" placeholder="Enter your name" aria-label="Your name" style="flex:1">
   <button class="btn" data-a="saveName">Continue →</button>
  </div>
  <p id="welcomeError" style="color:#ffb4b4;min-height:20px;margin-top:10px"></p>
 </div>
</div>`;
V.home=()=>{const avg=Math.round(topics.reduce((a,t)=>a+mastery(t),0)/topics.length),done=Object.values(db.qa).filter(x=>x.r>0).length,tl=(db.log.find(x=>x.d==today())||{n:0}).n;
 const weak=[...topics].sort((a,b)=>mastery(a)-mastery(b))[0],last=T(db.last)||weak;
 return`<div class="hero">${ring(avg,'#fff',92)}<div class="grow"><h1>Hello, ${esc(db.settings.name.split(' ')[0])} 👋</h1><p>${esc(db.settings.goal)}</p><div class="row" style="margin-top:12px"><a class="btn" style="background:#fff;color:#222;text-decoration:none" href="#lesson/${last.id}">▶ Continue: ${esc(last.title)}</a><a class="btn ghost" style="text-decoration:none" href="#oral">🎙️ Oral practice</a></div></div></div>
 <div class="stats"><div class="stat"><b>🔥 ${streak()}</b><small>day streak</small></div><div class="stat"><b>${tl}/${db.settings.daily}</b><small>today's goal</small></div><div class="stat"><b>${done}/65</b><small>Q&A answered</small></div><div class="stat"><b>${db.quiz.length}</b><small>quizzes taken</small></div></div>
 <div class="card">💡 <b>Smart tip:</b> ${mastery(weak)<100?`you need more practice with <a href="#lesson/${weak.id}">${esc(weak.title)}</a> (${mastery(weak)}% mastery).`:'you mastered every chapter — keep reviewing!'}${(()=>{const m=Object.entries(db.t).flatMap(([id,s])=>Object.entries(s.miss||{}).map(([k,n])=>[id,k,n])).sort((a,b)=>b[2]-a[2])[0];return m?` You often miss “${esc(m[1])}” in ${esc(T(m[0]).title)}.`:''})()}</div>
 <h2 class="sect">My 10 chapters</h2><div class="grid">${topics.map(tc).join('')}</div>`};
const tc=t=>`<a class="tcard" style="--c:${t.color}" href="#lesson/${t.id}"><span class="no">${String(t.no).padStart(2,'0')}</span><span class="em">${t.icon}</span><div><h3>${esc(t.title)}</h3><small>${esc(t.sub)}</small><div class="pb"><i style="width:${mastery(t)}%"></i></div></div></a>`;
V.learn=()=>`<h1 class="sect">📖 Lessons — Marc Asher's Study Notes</h1><div class="grid">${topics.map(tc).join('')}</div><div class="card" style="margin-top:14px"><b>🎙️ Comprehensive Q&A</b> — 65 questions. <a href="#oral">Start oral practice →</a></div>`;
V.lesson=(id,tab='learn')=>{const t=T(id);if(!t)return'<div class="card">Lesson not found.</div>';db.last=id;touch();const procs=t.blocks.map((b,i)=>b.p?i:-1).filter(i=>i>=0);
 const tabs=[['learn','📖 Learn'],['notebook','📄 Notebook'],...(procs.length?[['practice','🧤 Practice']]:[]),['quiz','🧪 Quiz'],['cards','🃏 Cards'],['notes','📝 My notes'],['ask','🤖 Ask AI']];
 let body='';
 if(tab=='learn')body=`<div class="row" style="margin-bottom:10px"><button class="btn sm" data-a="readall" data-id="${id}">🔊 Listen to chapter</button><button class="btn sm ghost" data-a="stop">⏹ Stop</button></div>`+t.blocks.map((b,i)=>blk(b,t,i)).join('');
 if(tab=='notebook')body=`<p style="color:var(--mute)">Your original notebook pages for this chapter — tap to zoom.</p><div class="gal">${(pages[t.id]||[]).map(p=>`<img loading="lazy" src="${p}" alt="Notebook page" data-a="zoom" data-src="${p}">`).join('')||'No pages.'}</div>`;
 if(tab=='practice')body=practice(t,procs);
 if(tab=='quiz')body=S.qz&&S.qz.tid==id?quizHTML():`<div class="card"><h3>🧪 ${esc(t.title)} quiz</h3><p>Questions are generated from your notes (facts, tables, step order).</p><button class="btn" data-a="qstart" data-id="${id}">Start quiz</button>${st(id).quiz!=null?` <span class="pill g">Best ${st(id).quiz}%</span>`:''}</div>`;
 if(tab=='cards')body=cardHTML(t);
 if(tab=='notes')body=`<div class="card"><h3>📝 My notes — ${esc(t.title)}</h3><textarea rows="9" data-c="note" data-id="${id}" placeholder="Write your own notes…">${esc(db.notes[id]||'')}</textarea></div>`;
 if(tab=='ask')body=chatHTML(id);
 return`<div class="th" style="--c:${t.color}"><span class="em">${t.icon}</span><div class="grow"><small>Chapter ${t.no}</small><h1>${esc(t.title)}</h1><small>${esc(t.sub)}</small></div>${ring(mastery(t),'#fff',70)}</div><div class="tabs" style="--c:${t.color}">${tabs.map(x=>`<button class="${tab==x[0]?'on':''}" data-a="go" data-to="lesson/${id}/${x[0]}">${x[1]}</button>`).join('')}</div><div style="--c:${t.color}">${body}</div>`};
function practice(t,procs){const P=S.pr&&S.pr.id==t.id?S.pr:null;
 if(!P)return`<div class="card"><h3>🧤 Choose a procedure to practice</h3><p>Learn → <b>Guided</b> (see each step) → <b>Memory</b> (steps hidden — recall, then reveal).</p>${procs.map(i=>`<div class="row" style="margin:8px 0"><b class="grow">${esc(t.blocks[i].h)}</b><button class="btn sm" data-a="pstart" data-id="${t.id}" data-bi="${i}" data-m="guided">Guided</button><button class="btn sm ghost" data-a="pstart" data-id="${t.id}" data-bi="${i}" data-m="memory">Memory</button></div>`).join('')}</div>`;
 const b=t.blocks[P.bi],n=b.i.length;if(P.i>=n){const ms=Object.keys(P.miss).length,sc=Math.round(100*(n-ms)/n);return`<div class="card" style="text-align:center"><div class="big">🎉 Sequence complete!</div>${ring(sc,'var(--ok)',100)}<p>${ms?`Difficult steps: ${Object.keys(P.miss).map(i=>+i+1).join(', ')}`:'No mistakes!'}</p><button class="btn" data-a="pdone">Save result</button> <button class="btn ghost" data-a="pstart" data-id="${t.id}" data-bi="${P.bi}" data-m="${P.m}">Again</button></div>`}
 return`<div class="card"><div class="row"><b class="grow">${esc(b.h)} · ${P.m=='memory'?'Memory':'Guided'}</b><span class="tag">Step ${P.i+1}/${n}</span></div>${bar(100*P.i/n)}<div class="big">${P.hide?'🙈 Recall this step from memory…':esc(b.i[P.i])}</div><div class="row" style="justify-content:center"><button class="btn ghost sm" data-a="preveal">${P.hide?'👁 Reveal':'🙈 Hide'}</button><button class="btn ghost sm" data-a="pspeak">🔊 Listen</button><button class="btn bad sm" data-a="pmiss">✗ Missed</button><button class="btn ok sm" data-a="pnext">✓ Got it</button></div></div>`}
function quizHTML(){const z=S.qz,q=z.qs[z.i];if(!q){const p=Math.round(100*z.s/z.qs.length);return`<div class="card" style="text-align:center"><div class="big">Score ${z.s}/${z.qs.length}</div>${ring(p,p>=70?'var(--ok)':'var(--warn)',100)}<p>${p>=80?'Excellent!':p>=50?'Good — review the ones you missed.':'Keep studying — you can do it!'}</p><button class="btn" data-a="qagain">Try again</button></div>`}
 return`<div class="card"><div class="row"><span class="tag">Question ${z.i+1}/${z.qs.length}</span></div>${bar(100*z.i/z.qs.length)}<h3 style="margin:14px 0">${esc(q.q)}</h3>${q.o.map((o,i)=>`<button class="opt ${z.pk!=null?(o==q.a?'good':i==z.pk?'wrong':''):''}" data-a="qpick" data-i="${i}" ${z.pk!=null?'disabled':''}>${esc(o)}</button>`).join('')}${z.pk!=null?`<button class="btn" data-a="qnext">Next ▶</button>`:''}</div>`}
function cardHTML(t){const C=S.cd&&S.cd.id==t.id?S.cd:(S.cd={id:t.id,i:0,f:false,deck:sh(cardsOf(t))});const c=C.deck[C.i%C.deck.length];if(!c)return'<div class="card">No cards.</div>';const k=Object.values(st(t.id).known).filter(Boolean).length;
 return`<div class="row"><span class="tag">Card ${C.i%C.deck.length+1}/${C.deck.length} · known ${k}</span></div><div class="flip" data-a="flip" style="margin:10px 0">${C.f?esc(c.b):esc(c.f)}</div><div class="row" style="justify-content:center"><button class="btn bad" data-a="know" data-k="${esc(c.k)}" data-v="0">Review again</button><button class="btn ok" data-a="know" data-k="${esc(c.k)}" data-v="1">I know it</button></div><p style="text-align:center;color:var(--mute)">Tap the card to flip</p>`}
V.cards=()=>`<h1 class="sect">🃏 Flashcards</h1><div class="grid">${topics.map(t=>`<a class="tcard" style="--c:${t.color}" href="#lesson/${t.id}/cards"><span class="em">${t.icon}</span><div><h3>${esc(t.title)}</h3><small>${tcards(t)} cards</small></div></a>`).join('')}</div>`;
V.quiz=()=>S.qz&&!S.qz.tid?`<div class="card">${quizHTML().replace('<div class="card">','').replace(/<\/div>$/,'')}</div>`:`<h1 class="sect">🧪 Quizzes</h1><div class="card"><b>Q&A challenge</b> — 10 random questions from your 65.<br><button class="btn" style="margin-top:8px" data-a="qstart" data-id="qa">Start</button></div><div class="grid">${topics.map(t=>`<a class="tcard" style="--c:${t.color}" href="#lesson/${t.id}/quiz"><span class="em">${t.icon}</span><div><h3>${esc(t.title)}</h3><small>${st(t.id).quiz!=null?'Best '+st(t.id).quiz+'%':'Not taken'}</small></div></a>`).join('')}</div>`;
/* oral */
const modes=[['practice','Practice'],['random','Random'],['weak','Weak areas'],['mock','Mock assessment'],['rapid','Rapid fire'],['full','Full 65']];
V.oral=()=>{const O=S.or;if(!O)return`<h1 class="sect">🎙️ 65-Item Oral Assessment</h1><div class="grid">${modes.map(m=>`<button class="card" style="text-align:left;color:inherit;cursor:pointer" data-a="ostart" data-m="${m[0]}"><h3>${m[1]}</h3><small style="color:var(--mute)">${{practice:'Question → answer → compare',random:'Shuffled questions',weak:'Questions you missed ('+Object.values(db.qa).filter(x=>x.w>0).length+')',mock:'10 questions, assessor style, final score',rapid:'Flip fast, self-check',full:'All 65 in order'}[m[0]]}</small></button>`).join('')}</div>`;
 if(O.i>=O.q.length){const avg=O.sc.length?Math.round(O.sc.reduce((a,b)=>a+b,0)/O.sc.length):0;return`<div class="card" style="text-align:center"><div class="big">Session complete</div>${ring(avg,avg>=60?'var(--ok)':'var(--warn)',100)}<p>${O.q.length} questions · ${O.m=='mock'?(avg>=70?'Assessor verdict: COMPETENT ✅':'Assessor verdict: needs more practice'):'average match '+avg+'%'}</p><button class="btn" data-a="ostart" data-m="${O.m}">Again</button> <button class="btn ghost" data-a="oexit">Menu</button></div>`}
 const x=O.q[O.i],r=O.r;
 return`<div class="card"><div class="row"><b class="grow">${modes.find(m=>m[0]==O.m)[1]}</b><span class="tag">${O.i+1}/${O.q.length} · Q${x.n}</span><button class="ico" data-a="oexit">✕</button></div>${bar(100*O.i/O.q.length)}<h2 style="margin:14px 0">${O.m=='mock'?'👩‍⚕️ Assessor: ':''}${esc(x.q)}</h2>
 ${O.m=='rapid'?`<div class="flip" data-a="orev">${O.rev?esc(x.a):'Tap to reveal'}</div>${O.rev?`<div class="row" style="justify-content:center;margin-top:10px"><button class="btn bad" data-a="orapid" data-v="0">Didn't know</button><button class="btn ok" data-a="orapid" data-v="1">Knew it</button></div>`:''}`:
 `<div class="row"><button class="btn ghost sm" data-a="oask">🔊 Ask me</button><button class="btn sm" data-a="omic" id="mic">🎙️ Answer by voice</button></div><textarea id="ans" rows="3" placeholder="Speak or type your answer…" style="margin-top:8px">${esc(O.ans||'')}</textarea><div class="row" style="margin-top:8px"><button class="btn ok" data-a="ocheck">Check answer</button></div>
 ${r?`<div class="res"><div class="card"><b>Your answer</b><br>${esc(O.ans||'—')}</div><div class="card"><b>Expected answer</b><br>${esc(x.a)}</div><div class="card"><b>Key points</b><br>${r.hit.map(w=>`<span class="pill g">✓ ${esc(w)}</span>`).join(' ')} ${r.miss.map(w=>`<span class="pill r">✗ ${esc(w)}</span>`).join(' ')}<h2 style="margin:10px 0 0">Score ${r.pct}%</h2></div><div id="aifb"></div><div class="row"><button class="btn ghost sm" data-a="oai">🤖 AI feedback</button><button class="btn ghost sm" data-a="oretry">Retry</button><button class="btn" data-a="onext">Next ▶</button></div></div>`:''}`}</div>`};
V.book=()=>{const ents=book.filter(e=>!e.micro&&!e.mem),by=id=>ents.filter(e=>e.t==id);const grp=(title,list)=>`<h2 class="sect">${title}</h2>`+list.map(e=>`<details class="card"><summary><b>${esc(e.title||e.q[0])}</b></summary><p style="white-space:pre-wrap">${esc(e.a)}</p>${e.q.length>1&&!e.n?`<small style="color:var(--mute)">Also answers: ${esc(e.q.slice(0,4).join(' · '))}</small>`:''}</details>`).join('');
 return`<h1 class="sect">📚 Q&A Book</h1><p style="color:var(--mute)">${ents.length} questions & answers from your notebook — this is what the offline tutor reads.</p><input id="bk" data-c="bk" placeholder="Filter the book…">`+topics.map(t=>grp(`${t.icon} ${t.no}. ${esc(t.title)}`,by(t.id))).join('')+grp('🎙️ Comprehensive Q&A (65)',by('qa'))};
V.tutor=(id)=>`<h1 class="sect">🤖 AI Tutor ${id&&T(id)?'— '+esc(T(id).title):''}</h1>${chatHTML(id)}`;
function chatHTML(id){const q=['Explain this simply','Quiz me on this','Give me a memory trick','What did I probably forget?','Tell me something current about caregiving'];
 return`<div class="card">${provider()=='offline'?`<div class="card" style="margin-bottom:10px">📴 <b>Offline tutor</b> — works with no internet, answers from your notebook's Q&A Book. For outside questions, connect an online AI in <a href="#settings">Settings</a>.</div>`:''}<div class="chat" id="chat" data-id="${id||''}">${db.chat.map(m=>`<div class="msg ${m.r=='user'?'u':'a'}">${esc(m.c)}</div>`).join('')||'<div class="msg a">Hi! Ask me anything — your lessons or anything else. I use your notebook first for caregiving.</div>'}</div><div class="row" style="margin:8px 0">${q.map(x=>`<button class="chip" style="color:inherit;cursor:pointer" data-a="qp" data-q="${esc(x)}">${esc(x)}</button>`).join('')}</div><div class="row"><textarea id="cin" rows="2" placeholder="Type or speak your question…" class="grow"></textarea><button class="ico" data-a="cmic" id="cmic">🎙️</button><button class="btn" data-a="csend">Send</button></div><div class="row" style="margin-top:6px"><label class="tog" style="margin:0"><input type="checkbox" data-c="autospeak" ${db.settings.autoSpeak?'checked':''}> read replies aloud</label><button class="btn ghost sm" data-a="cclear">Clear chat</button></div></div>`}
V.saved=()=>{const ms=db.marks.map(m=>{const[id,i]=m.split(':'),t=T(id);return t&&t.blocks[i]?{t,b:t.blocks[i]}:null}).filter(Boolean);
 return`<h1 class="sect">⭐ Bookmarks</h1>${ms.map(x=>`<div style="--c:${x.t.color}">${blk(x.b,x.t,x.t.blocks.indexOf(x.b))}</div>`).join('')||'<div class="card">No bookmarks yet — tap ☆ on any block in a lesson.</div>'}<h1 class="sect">📝 My notes</h1>${Object.entries(db.notes).filter(n=>n[1]&&T(n[0])).map(n=>`<div class="card"><b>${esc(T(n[0]).title)}</b><p style="white-space:pre-wrap">${esc(n[1])}</p><a href="#lesson/${n[0]}/notes">Edit</a></div>`).join('')||'<div class="card">No notes yet.</div>'}`};
V.progress=()=>{const z=db.quiz,ws=Object.entries(db.qa).filter(x=>x[1].w>0).sort((a,b)=>b[1].w-a[1].w);const misses=Object.entries(db.t).flatMap(([id,s])=>Object.entries(s.miss||{}).map(([k,n])=>`${T(id).title} — ${k} (${n}×)`));
 return`<h1 class="sect">📊 Progress</h1><div class="stats"><div class="stat"><b>${streak()}</b><small>streak</small></div><div class="stat"><b>${db.days.length}</b><small>study days</small></div><div class="stat"><b>${z.length}</b><small>quizzes</small></div><div class="stat"><b>${z.length?Math.round(z.reduce((a,x)=>a+100*x.s/x.n,0)/z.length):0}%</b><small>avg quiz</small></div></div><div class="card">${topics.map(t=>`<div class="row" style="margin:8px 0"><span style="width:32px">${t.icon}</span><b style="width:210px;max-width:46%">${esc(t.title)}</b><div class="grow">${bar(mastery(t))}</div><span>${mastery(t)}%</span></div>`).join('')}</div><div class="card"><b>Weak Q&A</b><ul>${ws.slice(0,8).map(w=>`<li>Q${w[0]}: ${esc(qa[w[0]-1].q)} (${w[1].w}×)</li>`).join('')||'<li>None yet</li>'}</ul><b>Difficult steps</b><ul>${misses.slice(0,8).map(m=>`<li>${esc(m)}</li>`).join('')||'<li>None yet</li>'}</ul></div>`};
V.settings=()=>{const s=db.settings,vs=voices();return`<h1 class="sect">⚙️ Settings & Profile</h1>
<div class="card"><h3>🎨 Appearance</h3><label>Theme</label><select data-c="set" data-k="theme">${['aurora','daylight','sakura','forest'].map(x=>`<option ${s.theme==x?'selected':''}>${x}</option>`).join('')}</select><label>Text size: ${s.fs}px</label><input type="range" min="14" max="22" value="${s.fs}" data-c="set" data-k="fs"><label class="tog">Animations <input type="checkbox" data-c="chk" data-k="motion" ${s.motion?'checked':''}></label></div>
<div class="card"><h3>🔊 Voice</h3><label>Voice</label><select data-c="set" data-k="voice"><option value="">Default</option>${vs.map(v=>`<option ${s.voice==v.name?'selected':''}>${esc(v.name)}</option>`).join('')}</select><label>Speech speed: ${s.rate}×</label><input type="range" min=".6" max="1.6" step=".1" value="${s.rate}" data-c="set" data-k="rate"><button class="btn sm ghost" data-a="vtest">Test voice</button></div>
<div class="card"><h3>🎯 Study</h3><label>Daily goal (activities)</label><input type="number" value="${s.daily}" min="1" data-c="set" data-k="daily"></div>
<div class="card"><h3>🤖 AI connection</h3><label>Provider</label><select data-c="prov">${[['offline','📴 Offline tutor (no internet, no setup)'],['proxy','Cloudflare Worker'],['anthropic','Claude API key (direct)'],['openai','OpenAI-compatible / Cloudflare AI endpoint']].map(x=>`<option value="${x[0]}" ${provider()==x[0]?'selected':''}>${x[1]}</option>`).join('')}</select>
${['anthropic','offline'].includes(provider())?'':`<label>${provider()=='proxy'?'Worker URL':'Endpoint URL (…/chat/completions)'}</label><input type="url" value="${esc(s.aiUrl)}" placeholder="${provider()=='proxy'?'https://carehub-ai.yourname.workers.dev':'https://api.cloudflare.com/client/v4/accounts/ID/ai/v1/chat/completions'}" data-c="set" data-k="aiUrl">`}
${['proxy','offline'].includes(provider())?'':`<label>API key / token</label><input type="password" value="${esc(s.aiKey)}" placeholder="${provider()=='anthropic'?'sk-ant-…':'Bearer token'}" data-c="set" data-k="aiKey">`}
${provider()=='offline'?'':`<label>Model</label><input value="${esc(s.aiModel)}" data-c="set" data-k="aiModel">`}
${['openai','offline'].includes(provider())?'':`<label class="tog">Allow web search (Claude) <input type="checkbox" data-c="chk" data-k="web" ${s.web!==false?'checked':''}></label>`}
<p style="color:var(--mute);font-size:.85rem">${{offline:'Works with no internet. Answers only from your notebook (65 Q&A + all chapters + extra phrasings). Add your own entries in js/data/extras.js.',proxy:'Deploy server/worker.js (see README). Backed by Claude (web search) or free Cloudflare Workers AI.',anthropic:'Key stays on this device only. Best for personal use.',openai:'Browsers often block direct Cloudflare API calls (CORS) — use the Worker option if the test fails.'}[provider()]}</p><button class="btn sm" data-a="aitest">Test connection</button> <span id="aist"></span></div>
<div class="card"><h3>👤 Profile</h3><label>Name</label><input value="${esc(s.name)}" data-c="set" data-k="name"><label>Address</label><input value="${esc(s.address)}" data-c="set" data-k="address"><label>School / course</label><input value="${esc(s.school)}" data-c="set" data-k="school"><label>My goal</label><input value="${esc(s.goal)}" data-c="set" data-k="goal"></div>
<div class="card"><h3>💾 Data</h3><div class="row"><button class="btn sm" data-a="exp">Export backup</button><label class="btn sm ghost" style="margin:0">Import<input type="file" accept=".json" data-c="imp" hidden></label><button class="btn sm bad" data-a="reset">Reset everything</button></div></div>
<div class="card"><h3>ℹ️ About</h3><p><b>CAREGIVING STUDY HUB</b> v2 — Made by MARC ASHER. Built from your notebook (10 chapters + 65 Q&A). Works offline once installed.</p></div>`};
/* ---------- search ---------- */
function search(q){q=q.toLowerCase();const r=[];topics.forEach(t=>{t.blocks.forEach(b=>{if(bt(b).toLowerCase().includes(q))r.push([`lesson/${t.id}`,`${t.icon} ${t.title}`,b.h||bt(b).slice(0,80)])});if((db.notes[t.id]||'').toLowerCase().includes(q))r.push([`lesson/${t.id}/notes`,'📝 My note',t.title])});qa.forEach(x=>(x.q+x.a).toLowerCase().includes(q)&&r.push(['oral','🎙️ Q&A '+x.n,x.q]));
 app.innerHTML=`<h1 class="sect">Search “${esc(q)}”</h1>`+(r.slice(0,40).map(x=>`<a class="card" style="display:block;text-decoration:none;color:inherit" href="#${x[0]}" data-a="clearq"><b>${esc(x[1])}</b><br>${esc(x[2])}</a>`).join('')||'<div class="card">No results.</div>')}
/* ---------- chat & AI ---------- */
async function send(text){if(!text.trim())return;const box=$('#chat');if(!box)return;const id=box.dataset.id,t=T(id);const add=(c,r)=>{const d=document.createElement('div');d.className='msg '+(r=='user'?'u':'a');d.textContent=c;box.appendChild(d);box.scrollTop=box.scrollHeight;return d};
 add(text,'user');db.chat.push({r:'user',c:text});bump();$('#cin').value='';
 if(provider()=='offline'){const r=offlineAnswer(text,id),d=add(r.text,'assistant');db.chat.push({r:'assistant',c:r.text});db.chat=db.chat.slice(-30);save();if(r.rel.length){const w=document.createElement('div');w.className='chips';w.style.marginTop='8px';w.innerHTML=r.rel.map(x=>`<button class="chip" style="color:inherit;cursor:pointer" data-a="qp" data-q="${esc(x)}">${esc(x)}</button>`).join('');d.appendChild(w)}if(db.settings.autoSpeak)say(r.text,{rate:rate(),voice:db.settings.voice});box.scrollTop=box.scrollHeight;return}
 const w=add('Thinking…','assistant');
 try{const hits=sh(qa.filter(x=>keyPoints(text).some(k=>(x.q+x.a).toLowerCase().includes(k)))).slice(0,6).map(x=>`Q${x.n} ${x.q} → ${x.a}`).join('\n');
  const ctx=(t?topicText(t):topics.map(topicText).join('\n'))+(hits?'\n# Related Q&A\n'+hits:'');
  const msgs=db.chat.slice(-12).map(m=>({role:m.r,content:m.c}));while(msgs.length&&msgs[0].role!='user')msgs.shift();
  const a=await chat(msgs,SYSTEM(ctx,db.settings.name));w.textContent=a;db.chat.push({r:'assistant',c:a});db.chat=db.chat.slice(-30);save();if(db.settings.autoSpeak)say(a,{rate:rate(),voice:db.settings.voice})}
 catch(e){w.textContent='⚠️ '+e.message;db.chat.pop()}box.scrollTop=box.scrollHeight}
/* ---------- actions ---------- */
const go=h=>{location.hash=h};
const A={go:d=>go(d.to),menu:()=>{$('#side').classList.toggle('open');$('#shade').classList.toggle('on')},closeMenu:()=>{$('#side').classList.remove('open');$('#shade').classList.remove('on')},
 zoom:d=>{$('#lb').innerHTML=`<img src="${d.src}">`;$('#lb').classList.add('on')},closeLb:()=>$('#lb').classList.remove('on'),clearq:()=>{$('#q').value=''},
 mark:d=>{const k=d.id+':'+d.i,i=db.marks.indexOf(k);i<0?db.marks.push(k):db.marks.splice(i,1);save();toast(i<0?'⭐ Bookmarked':'Removed');render()},
 readb:d=>{const t=T(d.id);say(bt(t.blocks[d.i]),{rate:rate(),voice:db.settings.voice})||toast('Speech not supported')},readall:d=>say(T(d.id).blocks.map(bt),{rate:rate(),voice:db.settings.voice}),stop:()=>stop(),
 pstart:d=>{S.pr={id:d.id,bi:+d.bi,m:d.m,i:0,hide:d.m=='memory',miss:{}};render()},preveal:()=>{S.pr.hide=!S.pr.hide;render()},pspeak:()=>{const P=S.pr;say(T(P.id).blocks[P.bi].i[P.i],{rate:rate(),voice:db.settings.voice})},
 pmiss:()=>{const P=S.pr,b=T(P.id).blocks[P.bi];P.miss[P.i]=1;const s=st(P.id);const k='Step '+(P.i+1)+' of '+b.h;s.miss[k]=(s.miss[k]||0)+1;save();toast('Marked as difficult');},
 pnext:()=>{const P=S.pr;P.i++;P.hide=P.m=='memory';bump();render()},pdone:()=>{const P=S.pr,n=T(P.id).blocks[P.bi].i.length,s=st(P.id);s.prac=Math.max(s.prac||0,Math.round(100*(n-Object.keys(P.miss).length)/n));save();S.pr=null;toast('Saved ✓');render()},
 qstart:d=>{const t=T(d.id);S.qz={tid:t?t.id:null,i:0,s:0,pk:null,qs:t?genQuiz(t):qaQuiz()};render()},qagain:()=>{const z=S.qz;S.qz={tid:z.tid,i:0,s:0,pk:null,qs:z.tid?genQuiz(T(z.tid)):qaQuiz()};render()},
 qpick:d=>{const z=S.qz,q=z.qs[z.i];z.pk=+d.i;const ok=q.o[z.pk]==q.a;if(ok)z.s++;if(q.id){const r=db.qa[q.id]=db.qa[q.id]||{r:0,w:0};ok?r.r++:r.w++}save();render()},
 qnext:()=>{const z=S.qz;z.i++;z.pk=null;bump();if(z.i>=z.qs.length){const p=Math.round(100*z.s/z.qs.length);db.quiz.push({d:Date.now(),s:z.s,n:z.qs.length,t:z.tid});if(z.tid){const s=st(z.tid);s.quiz=Math.max(s.quiz||0,p)}save()}render()},
 flip:()=>{S.cd.f=!S.cd.f;render()},know:d=>{st(S.cd.id).known[d.k]=+d.v;S.cd.i++;S.cd.f=false;bump();save();render()},
 ostart:d=>{const m=d.m;let q=m=='weak'?qa.filter(x=>db.qa[x.n]?.w>0):m=='full'?[...qa]:m=='practice'?qa.slice(db.oi||0).concat(qa.slice(0,db.oi||0)).slice(0,20):sh(qa).slice(0,m=='mock'?10:m=='rapid'?20:65);if(!q.length){toast('No weak questions yet 🎉');return}S.or={m,q,i:0,r:null,ans:'',sc:[],rev:false};render()},oexit:()=>{S.or=null;stop();render()},
 oask:()=>say(S.or.q[S.or.i].q,{rate:rate(),voice:db.settings.voice}),
 omic:()=>{const b=$('#mic');b.textContent='🔴 Listening…';listen(t=>{$('#ans').value=t},f=>{b.textContent='🎙️ Answer by voice';S.or.ans=$('#ans').value},e=>{toast(e);b.textContent='🎙️ Answer by voice'})},
 ocheck:()=>{const O=S.or,x=O.q[O.i];O.ans=$('#ans').value;O.r=grade(O.ans,x.a);O.sc[O.i]=O.r.pct;const r=db.qa[x.n]=db.qa[x.n]||{r:0,w:0};O.r.pct>=50?r.r++:r.w++;db.oi=x.n%65;bump();save();render()},
 oretry:()=>{S.or.r=null;render()},onext:()=>{const O=S.or;O.i++;O.r=null;O.ans='';O.rev=false;render()},orev:()=>{S.or.rev=!S.or.rev;render()},
 orapid:d=>{const O=S.or,x=O.q[O.i],r=db.qa[x.n]=db.qa[x.n]||{r:0,w:0};+d.v?r.r++:r.w++;O.sc[O.i]=+d.v*100;bump();save();A.onext()},
 oai:async()=>{const O=S.or,x=O.q[O.i],e=$('#aifb');if(provider()=='offline'){const r=O.r;e.innerHTML=`<div class="card">📴 <b>Offline feedback</b><br>${r.pct>=70?'Strong answer!':r.pct>=40?'Partly there.':'Needs review.'} You covered ${r.hit.length} of ${r.hit.length+r.miss.length} key points. Focus on: ${esc(r.miss.slice(0,5).join(', ')||'nothing — great!')}. Compare with the expected answer above, then retry.</div>`;return}e.innerHTML='<div class="card">Examining…</div>';try{const a=await chat([{role:'user',content:`Question: ${x.q}\nExpected answer (from my notebook): ${x.a}\nMy answer: ${O.ans||'(blank)'}\nAs a caregiving oral assessor: say what I got right, what I missed, give constructive feedback and a score out of 10. Be brief.`}],SYSTEM('Oral Q&A item','the student'));e.innerHTML=`<div class="card" style="white-space:pre-wrap">🤖 ${esc(a)}</div>`;if(db.settings.autoSpeak)say(a,{rate:rate()})}catch(er){e.innerHTML='<div class="card warn">'+esc(er.message)+'</div>'}},
 qp:d=>{$('#cin').value=d.q;A.csend()},csend:()=>send($('#cin').value),cclear:()=>{db.chat=[];save();render()},
 cmic:()=>{const b=$('#cmic');b.textContent='🔴';listen(t=>{$('#cin').value=t},f=>{b.textContent='🎙️';f&&A.csend()},e=>{toast(e);b.textContent='🎙️'})},
 vtest:()=>say('Hello '+(db.settings.name?.split(' ')[0]||'there')+'. Let us review your caregiving lessons.',{rate:rate(),voice:db.settings.voice}),
 aitest:async()=>{const e=$('#aist');if(provider()=='offline'){e.textContent='✅ Offline tutor ready ('+book.length+' book entries)';return}e.textContent='Testing…';try{const a=await chat([{role:'user',content:'Reply with: connected'}],'Be brief.');e.textContent='✅ '+a.slice(0,40)}catch(er){e.textContent='❌ '+er.message}},
 exp:()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([exportData()],{type:'application/json'}));a.download='carehub-backup.json';a.click()},reset:()=>{confirm('Erase ALL progress, notes and settings on this device?')&&reset()},
 saveName:()=>{const el=$('#welcomeName');const name=(el?.value||'').trim();if(!name){const er=$('#welcomeError');if(er)er.textContent='Please enter your name.';el?.focus();return}db.settings.name=name;save();render()},
 install:async()=>{if(window._ip){window._ip.prompt();window._ip=null;$('#install').hidden=true}}};
document.addEventListener('click',e=>{const a=e.target.closest('[data-a]');if(!a||!A[a.dataset.a])return;if(a.tagName=='A'&&a.dataset.a!='clearq')e.preventDefault();stop&&0;A[a.dataset.a](a.dataset,a);if(a.dataset.a!='menu')$('#side').classList.remove('open'),$('#shade').classList.remove('on')});
document.addEventListener('input',e=>{const c=e.target.dataset.c;if(c=='bk'){const q=e.target.value.toLowerCase();document.querySelectorAll('#app details').forEach(d=>d.style.display=d.textContent.toLowerCase().includes(q)?'':'none')}if(c=='note'){db.notes[e.target.dataset.id]=e.target.value;save()}});
document.addEventListener('change',e=>{const el=e.target,c=el.dataset.c;if(c=='set'){const k=el.dataset.k;db.settings[k]=['fs','rate','daily'].includes(k)?+el.value:el.value;save();applySet();if(['fs','rate'].includes(k))render()}
 if(c=='prov'){db.settings.aiProvider=el.value;save();render()}if(c=='chk'){db.settings[el.dataset.k]=el.checked;save();applySet()}if(c=='autospeak'){db.settings.autoSpeak=el.checked;save()}
 if(c=='imp'&&el.files[0])el.files[0].text().then(t=>{try{importData(t);applySet();toast('Imported ✓');render()}catch{toast('Invalid file')}})});
$('#q').addEventListener('input',e=>{const q=e.target.value.trim();q.length>1?search(q):render()});
addEventListener('beforeinstallprompt',e=>{e.preventDefault();window._ip=e;$('#install').hidden=false});
addEventListener('hashchange',()=>{if(location.hash.slice(1).split('/')[0]!='lesson')S.cd=null;render();scrollTo(0,0)});
function render(){const[p,a,b]=location.hash.slice(1).split('/');const needsName=!db.settings.name||db.settings.name.trim()===''||db.settings.name.trim().toLowerCase()=='marc asher';const page=needsName?'welcome':(V[p]?p:'home');
 document.querySelectorAll('#nav a,#tabbar a').forEach(x=>x.classList.toggle('on',x.dataset.p==page||(page=='lesson'&&x.dataset.p=='learn')));
 try{app.innerHTML=V[page](a,b);if(page=='welcome')setTimeout(()=>$('#welcomeName')?.focus(),0)}catch(e){console.error(e);app.innerHTML='<div class="card warn">Something went wrong: '+esc(e.message)+'</div>'}
 if(page=='tutor'||b=='ask'){const c=$('#chat');c&&(c.scrollTop=c.scrollHeight)}}
applySet();touch();render();
